# Generated by Django 3.2.25 on 2024-11-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241116_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispenserconfig',
            old_name='timestamp',
            new_name='time',
        ),
    ]
