# Generated by Django 3.2.25 on 2024-11-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_timestamp_dispenserconfig_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_pet_name_per_user'),
        ),
    ]
